# Generated by Django 4.2.2 on 2023-06-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('domain', models.CharField(blank=True, db_column='Domain', max_length=255, null=True)),
                ('selected', models.CharField(blank=True, db_column='Selected', max_length=255, null=True)),
                ('control', models.CharField(blank=True, db_column='Control', max_length=255, null=True)),
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('control_description', models.CharField(blank=True, db_column='Control Description', max_length=255, null=True)),
                ('methods_to_comply_with_control', models.CharField(blank=True, db_column='Methods To Comply With Control', max_length=255, null=True)),
                ('evidence_request_references', models.CharField(blank=True, db_column='Evidence Request References', max_length=255, null=True)),
                ('control_question', models.CharField(blank=True, db_column='Control Question', max_length=255, null=True)),
                ('campo9', models.CharField(blank=True, db_column='Campo9', max_length=255, null=True)),
                ('campo10', models.TextField(blank=True, db_column='Campo10', null=True)),
                ('campo11', models.TextField(blank=True, db_column='Campo11', null=True)),
                ('campo12', models.TextField(blank=True, db_column='Campo12', null=True)),
                ('campo13', models.TextField(blank=True, db_column='Campo13', null=True)),
                ('campo14', models.TextField(blank=True, db_column='Campo14', null=True)),
                ('assessment_question_evidences_comments', models.CharField(blank=True, db_column='Assessment Question/Evidences Comments', max_length=255, null=True)),
                ('assesed_result', models.CharField(blank=True, db_column='Assesed result', max_length=255, null=True)),
                ('control_assessment_comments2', models.CharField(blank=True, db_column='Control Assessment Comments2', max_length=255, null=True)),
            ],
            options={
                'db_table': 'assessment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CisCscV8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('cis_csc_v8_0', models.CharField(blank=True, db_column='CIS CSC v8 0', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cis csc v8',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cobit2019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('cobit_2019', models.CharField(blank=True, db_column='COBIT 2019', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cobit 2019',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('Ccmmcod', models.CharField(db_column='Identifier', max_length=255, primary_key=True, serialize=False)),
                ('domain', models.CharField(blank=True, db_column='Domain', max_length=255, null=True)),
                ('security_privacy_by_design_s_p_principles', models.CharField(blank=True, db_column='Security & Privacy by Design (S|P) Principles', max_length=255, null=True)),
                ('principle_intent', models.TextField(blank=True, db_column='Principle Intent', null=True)),
            ],
            options={
                'db_table': 'domains',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenceRequestCatalog',
            fields=[
                ('evidence_request_references', models.CharField(db_column='Evidence Request References', max_length=255, primary_key=True, serialize=False)),
                ('area_of_focus', models.CharField(blank=True, db_column='Area of Focus', max_length=255, null=True)),
                ('artifact', models.CharField(blank=True, db_column='Artifact', max_length=255, null=True)),
                ('artifact_description', models.TextField(blank=True, db_column='Artifact Description', null=True)),
                ('control_mappings', models.CharField(blank=True, db_column='Control Mappings', max_length=255, null=True)),
            ],
            options={
                'db_table': 'evidence request catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrameworkList',
            fields=[
                ('framework_name', models.CharField(blank=True, db_column='Framework Name', max_length=255, null=True)),
                ('table_name', models.CharField(blank=True, db_column='Table Name', max_length=255, null=True)),
                ('framework_id', models.CharField(db_column='Framework ID', max_length=255, primary_key=True, serialize=False)),
                ('selected', models.IntegerField(blank=True, db_column='Selected', null=True)),
            ],
            options={
                'db_table': 'framework list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso270012022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso_27001_v2022', models.CharField(blank=True, db_column='ISO 27001 v2022', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso 27001 2022',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso270022022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso_27002_v2022', models.CharField(blank=True, db_column='ISO 27002 v2022', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso 27002 2022',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaturirtyTable',
            fields=[
                ('ccmmcod', models.CharField(blank=True, db_column='CCMMCOD', max_length=255, null=True)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=255, null=True)),
                ('sublevels', models.CharField(db_column='SUBLEVELS', max_length=255, primary_key=True, serialize=False)),
                ('percentage', models.FloatField(blank=True, db_column='PERCENTAGE', null=True)),
            ],
            options={
                'db_table': 'maturirty table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NttcsCf20231',
            fields=[
                ('domain', models.CharField(blank=True, db_column='Domain', max_length=255, null=True)),
                ('selected_y_n_field', models.CharField(blank=True, db_column='Selected? (Y/N)', max_length=255, null=True)),
                ('control', models.CharField(blank=True, db_column='Control', max_length=255, null=True)),
                ('id', models.CharField(db_column='ID', max_length=255, primary_key=True, serialize=False)),
                ('control_description', models.CharField(blank=True, db_column='Control Description', max_length=255, null=True)),
                ('relative_control_weighting', models.FloatField(blank=True, db_column='Relative Control Weighting', null=True)),
                ('function_grouping', models.CharField(blank=True, db_column='Function Grouping', max_length=255, null=True)),
                ('scrm1', models.CharField(blank=True, db_column='SCRM1', max_length=255, null=True)),
                ('scrm2', models.CharField(blank=True, db_column='SCRM2', max_length=255, null=True)),
                ('scrm3', models.CharField(blank=True, db_column='SCRM3', max_length=255, null=True)),
                ('assesed_result', models.CharField(blank=True, db_column='Assesed result', max_length=255, null=True)),
                ('numeric_result', models.CharField(blank=True, db_column='Numeric result', max_length=255, null=True)),
                ('weighted_numeric_result', models.FloatField(blank=True, db_column='Weighted Numeric result', null=True)),
                ('assessment_comments', models.CharField(blank=True, db_column='Assessment Comments', max_length=255, null=True)),
                ('relative_result_by_function', models.FloatField(blank=True, db_column='Relative result by Function', null=True)),
                ('relative_result_by_domain', models.FloatField(blank=True, db_column='Relative result by Domain', null=True)),
            ],
            options={
                'db_table': 'nttcs cf 2023 1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiskCatalog',
            fields=[
                ('risk_grouping', models.CharField(blank=True, db_column='Risk Grouping', max_length=255, null=True)),
                ('risk_id', models.CharField(db_column='Risk ID', max_length=255, primary_key=True, serialize=False)),
                ('risk', models.CharField(blank=True, db_column='Risk', max_length=255, null=True)),
                ('description_of_possible_risk_due_to_control_deficiency', models.CharField(blank=True, db_column='Description of Possible Risk Due To Control Deficiency', max_length=255, null=True)),
                ('frequency', models.CharField(blank=True, db_column='Frequency', max_length=255, null=True)),
                ('freqnum', models.FloatField(blank=True, db_column='FreqNum', null=True)),
                ('impact', models.CharField(blank=True, db_column='Impact', max_length=255, null=True)),
                ('impactnum', models.FloatField(blank=True, db_column='ImpactNum', null=True)),
                ('risk_val', models.FloatField(blank=True, db_column='Risk Val', null=True)),
                ('function', models.CharField(blank=True, db_column='Function', max_length=255, null=True)),
            ],
            options={
                'db_table': 'risk catalog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThreatCatalog',
            fields=[
                ('threat_group', models.CharField(blank=True, db_column='Threat Group', max_length=255, null=True)),
                ('threat_id', models.CharField(db_column='Threat ID', max_length=255, primary_key=True, serialize=False)),
                ('threat', models.CharField(blank=True, db_column='Threat', max_length=255, null=True)),
                ('threat_description', models.TextField(blank=True, db_column='Threat Description', null=True)),
            ],
            options={
                'db_table': 'threat catalog',
                'managed': False,
            },
        ),
    ]
