# Generated by Django 4.2.2 on 2023-06-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsociacionMarcos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marco_id', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_tabla', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'asociacion_marcos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assessmentguardados',
            fields=[
                ('id_assessment', models.CharField(db_column='ID_assessment', max_length=100, primary_key=True, serialize=False)),
                ('marcos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessmentguardados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('ntt_id', models.AutoField(db_column='NTT_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('ntt_id', models.BigAutoField(db_column='NTT_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('ntt_id', models.AutoField(db_column='NTT_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('ntt_id', models.AutoField(db_column='NTT_ID', primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('ntt_id', models.BigAutoField(db_column='NTT_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('ntt_id', models.BigAutoField(db_column='NTT_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cosov2017',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('cosov2017', models.CharField(blank=True, db_column='COSOv2017', max_length=255, null=True)),
            ],
            options={
                'db_table': 'cosov2017',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Csaccmv4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('csaccmv4', models.CharField(blank=True, db_column='CSACCMv4', max_length=255, null=True)),
            ],
            options={
                'db_table': 'csaccmv4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Csaiotscfv2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('csaiotscfv2', models.CharField(blank=True, db_column='CSAIoTSCFv2', max_length=255, null=True)),
            ],
            options={
                'db_table': 'csaiotscfv2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emeaeudora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('emeaeudora', models.CharField(blank=True, db_column='EMEAEUDORA', max_length=255, null=True)),
            ],
            options={
                'db_table': 'emeaeudora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmeaeueprivacyDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('emeaeueprivacy_draft_field', models.CharField(blank=True, db_column='EMEAEUePrivacy(draft)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'emeaeueprivacy(draft)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emeaeugdpr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('emeaeugdpr', models.CharField(blank=True, db_column='EMEAEUGDPR', max_length=255, null=True)),
            ],
            options={
                'db_table': 'emeaeugdpr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emeaeupsd2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('emeaeupsd2', models.CharField(blank=True, db_column='EMEAEUPSD2', max_length=255, null=True)),
            ],
            options={
                'db_table': 'emeaeupsd2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emeaspain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('emeaspain', models.CharField(blank=True, db_column='EMEASpain', max_length=255, null=True)),
            ],
            options={
                'db_table': 'emeaspain',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emeaspainccnstic825',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('emeaspainccnstic825', models.CharField(blank=True, db_column='EMEASpainCCNSTIC825', max_length=255, null=True)),
            ],
            options={
                'db_table': 'emeaspainccnstic825',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enisav2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('enisav2', models.CharField(blank=True, db_column='ENISAv2', max_length=255, null=True)),
            ],
            options={
                'db_table': 'enisav2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hipaahicplargepractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('hipaahicplargepractice', models.CharField(blank=True, db_column='HIPAAHICPLargePractice', max_length=255, null=True)),
            ],
            options={
                'db_table': 'hipaahicplargepractice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hipaahicpmediumpractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('hipaahicpmediumpractice', models.CharField(blank=True, db_column='HIPAAHICPMediumPractice', max_length=255, null=True)),
            ],
            options={
                'db_table': 'hipaahicpmediumpractice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hipaahicpsmallpractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('hipaahicpsmallpractice', models.CharField(blank=True, db_column='HIPAAHICPSmallPractice', max_length=255, null=True)),
            ],
            options={
                'db_table': 'hipaahicpsmallpractice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identifydiscretionarysecurityre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('identifydiscretionarysecurityrequirements_dsr_field', models.CharField(blank=True, db_column='IdentifyDiscretionarySecurityRequirements(DSR)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'identifydiscretionarysecurityre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Identifyminimumcompliancecontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('identifyminimumcompliancecontrols_mcc_field', models.CharField(blank=True, db_column='IdentifyMinimumComplianceControls(MCC)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'identifyminimumcompliancecontro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iec6244342',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iec6244342', models.CharField(blank=True, db_column='IEC6244342', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iec6244342',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso22301V2019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso22301v2019', models.CharField(blank=True, db_column='ISO22301v2019', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso22301v2019',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso27001V2013',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso27001v2013', models.CharField(blank=True, db_column='ISO27001v2013', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso27001v2013',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso27001V2022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso27001v2022', models.CharField(blank=True, db_column='ISO27001v2022', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso27001v2022',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso27002V2013',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso27002v2013', models.CharField(blank=True, db_column='ISO27002v2013', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso27002v2013',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso27002V2022',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso27002v2022', models.CharField(blank=True, db_column='ISO27002v2022', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso27002v2022',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso27017V2015',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso27017v2015', models.CharField(blank=True, db_column='ISO27017v2015', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso27017v2015',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso27018V2014',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso_27018v2014', models.CharField(blank=True, db_column='ISO 27018v2014', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso 27018v2014',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso27701V2019',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso27701_v2019', models.CharField(blank=True, db_column='ISO27701 v2019', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso27701 v2019',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso29100V2011',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso29100v2011', models.CharField(blank=True, db_column='ISO29100v2011', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso29100v2011',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso31000V2009',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso31000v2009', models.CharField(blank=True, db_column='ISO31000v2009', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso31000v2009',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Iso31010V2009',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('iso31010v2009', models.CharField(blank=True, db_column='ISO31010v2009', max_length=255, null=True)),
            ],
            options={
                'db_table': 'iso31010v2009',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Minimumsecurityrequirementsmcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('minimumsecurityrequirementsmcc_dsr', models.CharField(blank=True, db_column='MinimumSecurityRequirementsMCC+DSR', max_length=255, null=True)),
            ],
            options={
                'db_table': 'minimumsecurityrequirementsmcc+',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist800160',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist800160', models.CharField(blank=True, db_column='NIST800160', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist800160',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist800161Rev1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist800161rev1', models.CharField(blank=True, db_column='NIST800161rev1', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist800161rev1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist800161Rev1Cscrmbaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist800161rev1cscrmbaseline', models.CharField(blank=True, db_column='NIST800161rev1CSCRMBaseline', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist800161rev1cscrmbaseline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist800161Rev1FlowDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist800161rev1flow_down', models.CharField(blank=True, db_column='NIST800161rev1Flow Down', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist800161rev1flow down',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist800161Rev1Level1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist800161rev1level1', models.CharField(blank=True, db_column='NIST800161rev1Level1', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist800161rev1level1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist800161Rev1Level2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist800161rev1level2', models.CharField(blank=True, db_column='NIST800161rev1Level2', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist800161rev1level2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist800161Rev1Level3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist800161rev1level3', models.CharField(blank=True, db_column='NIST800161rev1Level3', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist800161rev1level3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist800171A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist800171a', models.CharField(blank=True, db_column='NIST800171A', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist800171a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist800171Rev2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist800171rev2', models.CharField(blank=True, db_column='NIST800171rev2', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist800171rev2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist800172',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist800172', models.CharField(blank=True, db_column='NIST800172', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist800172',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist800218V11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist800218v1_1', models.CharField(blank=True, db_column='NIST800218v1_1', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist800218v1_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80037Rev2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80037rev2', models.CharField(blank=True, db_column='NIST80037rev2', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80037rev2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80039',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80039', models.CharField(blank=True, db_column='NIST80039', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80039',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80053Rev4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80053rev4', models.CharField(blank=True, db_column='NIST80053rev4', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80053rev4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80053Rev4High',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80053rev4_high_field', models.CharField(blank=True, db_column='NIST80053rev4(high)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80053rev4(high)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80053Rev4Low',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80053rev4_low_field', models.CharField(blank=True, db_column='NIST80053rev4(low)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80053rev4(low)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80053Rev4Moderate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80053rev4_moderate_field', models.CharField(blank=True, db_column='NIST80053rev4(moderate)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80053rev4(moderate)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80053Rev5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80053rev5', models.CharField(blank=True, db_column='NIST80053rev5', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80053rev5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80053Rev5High',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80053rev5_high_field', models.CharField(blank=True, db_column='NIST80053rev5(high)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80053rev5(high)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80053Rev5Low',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80053rev5_low_field', models.CharField(blank=True, db_column='NIST80053rev5(low)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80053rev5(low)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80053Rev5Moderate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80053rev5_moderate_field', models.CharField(blank=True, db_column='NIST80053rev5(moderate)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80053rev5(moderate)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80053Rev5Noc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80053rev5_noc_field', models.CharField(blank=True, db_column='NIST80053rev5(NOC)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80053rev5(noc)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80053Rev5Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80053rev5_privacy_field', models.CharField(blank=True, db_column='NIST80053rev5(privacy)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80053rev5(privacy)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80063BPartialmapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80063b_partialmapping_field', models.CharField(blank=True, db_column='NIST80063B(partialmapping)', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80063b(partialmapping)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80082Rev2Highimpacticsoverl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80082rev2highimpacticsoverlay', models.CharField(blank=True, db_column='NIST80082rev2HighImpactICSOverlay', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80082rev2highimpacticsoverl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80082Rev2Lowimpacticsoverla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80082rev2lowimpacticsoverlay', models.CharField(blank=True, db_column='NIST80082rev2LowImpactICSOverlay', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80082rev2lowimpacticsoverla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nist80082Rev2Moderateimpacticso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nist80082rev2moderateimpacticsoverlay', models.CharField(blank=True, db_column='NIST80082rev2ModerateImpactICSOverlay', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nist80082rev2moderateimpacticso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nistarmfai1001V1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nistarmfai1001v1', models.CharField(blank=True, db_column='NISTARMFAI1001v1', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nistarmfai1001v1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nistcsfv11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nistcsfv1_1', models.CharField(blank=True, db_column='NISTCSFv1_1', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nistcsfv1_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nistprivacyframeworkv1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nistprivacyframeworkv1', models.CharField(blank=True, db_column='NISTPrivacyFrameworkv1', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nistprivacyframeworkv1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nistssdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('nistssdf', models.CharField(blank=True, db_column='NISTSSDF', max_length=255, null=True)),
            ],
            options={
                'db_table': 'nistssdf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Owasptop10V2021',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('owasptop10v2021', models.CharField(blank=True, db_column='OWASPTop10v2021', max_length=255, null=True)),
            ],
            options={
                'db_table': 'owasptop10v2021',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pcidssv32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('pcidssv3_2', models.CharField(blank=True, db_column='PCIDSSv3_2', max_length=255, null=True)),
            ],
            options={
                'db_table': 'pcidssv3_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pcidssv40',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('pcidssv4_0', models.CharField(blank=True, db_column='PCIDSSv4_0', max_length=255, null=True)),
            ],
            options={
                'db_table': 'pcidssv4_0',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScfbbusinessmergersAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('scfbbusinessmergers_acquisitions', models.CharField(blank=True, db_column='SCFBBusinessMergers&Acquisitions', max_length=255, null=True)),
            ],
            options={
                'db_table': 'scfbbusinessmergers&acquisition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scfeembeddedtechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('scfeembeddedtechnology', models.CharField(blank=True, db_column='SCFEEmbeddedTechnology', max_length=255, null=True)),
            ],
            options={
                'db_table': 'scfeembeddedtechnology',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scficyberinsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('scficyberinsurance', models.CharField(blank=True, db_column='SCFICyberInsurance', max_length=255, null=True)),
            ],
            options={
                'db_table': 'scficyberinsurance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scfrransomwareprotection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('scfrransomwareprotection', models.CharField(blank=True, db_column='SCFRRansomwareProtection', max_length=255, null=True)),
            ],
            options={
                'db_table': 'scfrransomwareprotection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usc2M2V21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('usc2m2v2_1', models.CharField(blank=True, db_column='USC2M2v2_1', max_length=255, null=True)),
            ],
            options={
                'db_table': 'usc2m2v2_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uscertrmmv12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idntt_id', models.CharField(blank=True, db_column='IDNTT_ID', max_length=255, null=True)),
                ('uscertrmmv1_2', models.CharField(blank=True, db_column='USCERTRMMv1_2', max_length=255, null=True)),
            ],
            options={
                'db_table': 'uscertrmmv1_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uscmmc20Level1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('uscmmc2_0level_1', models.CharField(blank=True, db_column='USCMMC2_0Level 1', max_length=255, null=True)),
            ],
            options={
                'db_table': 'uscmmc2_0level 1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uscmmc20Level2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('uscmmc2_0level2', models.CharField(blank=True, db_column='USCMMC2_0Level2', max_length=255, null=True)),
            ],
            options={
                'db_table': 'uscmmc2_0level2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uscmmc20Level3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('uscmmc2_0level3', models.CharField(blank=True, db_column='USCMMC2_0Level3', max_length=255, null=True)),
            ],
            options={
                'db_table': 'uscmmc2_0level3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ushipaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('ushipaa', models.CharField(blank=True, db_column='USHIPAA', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ushipaa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ussox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntt_id', models.CharField(blank=True, db_column='NTT_ID', max_length=255, null=True)),
                ('ussox', models.CharField(blank=True, db_column='USSOX', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ussox',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Iso270012022',
        ),
        migrations.DeleteModel(
            name='Iso270022022',
        ),
        migrations.AlterModelTable(
            name='ciscscv8',
            table='ciscscv8',
        ),
        migrations.AlterModelTable(
            name='cobit2019',
            table='cobit2019',
        ),
    ]
