# Generated by Django 4.2.2 on 2023-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_asociacionmarcos_assessmentguardados_authgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeleccionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
