# Generated by Django 4.2.2 on 2023-08-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_assessmentcreados'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsociacionEvidenciasCreadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asociacion_evidencias_creadas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsociacionEvidenciasGenericas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asociacion_evidencias_genericas',
                'managed': False,
            },
        ),
    ]
