# Generated by Django 4.2.2 on 2023-07-13 12:38

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_seleccionassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pass_field', models.CharField(db_column='pass', max_length=100)),
                ('rol', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Evidencias',
            fields=[
                ('evidencia_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, db_column='Comentario', null=True)),
                ('links', models.TextField(blank=True, null=True)),
                ('control_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'evidencias',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CisCscV8',
        ),
        migrations.DeleteModel(
            name='Cobit2019',
        ),
        migrations.DeleteModel(
            name='Cosov2017',
        ),
        migrations.DeleteModel(
            name='Csaccmv4',
        ),
        migrations.DeleteModel(
            name='Csaiotscfv2',
        ),
        migrations.DeleteModel(
            name='Emeaeudora',
        ),
        migrations.DeleteModel(
            name='EmeaeueprivacyDraft',
        ),
        migrations.DeleteModel(
            name='Emeaeugdpr',
        ),
        migrations.DeleteModel(
            name='Emeaeupsd2',
        ),
        migrations.DeleteModel(
            name='Emeaspain',
        ),
        migrations.DeleteModel(
            name='Emeaspainccnstic825',
        ),
        migrations.DeleteModel(
            name='Enisav2',
        ),
        migrations.DeleteModel(
            name='FrameworkList',
        ),
        migrations.DeleteModel(
            name='Hipaahicplargepractice',
        ),
        migrations.DeleteModel(
            name='Hipaahicpmediumpractice',
        ),
        migrations.DeleteModel(
            name='Hipaahicpsmallpractice',
        ),
        migrations.DeleteModel(
            name='Identifydiscretionarysecurityre',
        ),
        migrations.DeleteModel(
            name='Identifyminimumcompliancecontro',
        ),
        migrations.DeleteModel(
            name='Iec6244342',
        ),
        migrations.DeleteModel(
            name='Iso22301V2019',
        ),
        migrations.DeleteModel(
            name='Iso27001V2013',
        ),
        migrations.DeleteModel(
            name='Iso27001V2022',
        ),
        migrations.DeleteModel(
            name='Iso27002V2013',
        ),
        migrations.DeleteModel(
            name='Iso27002V2022',
        ),
        migrations.DeleteModel(
            name='Iso27017V2015',
        ),
        migrations.DeleteModel(
            name='Iso27018V2014',
        ),
        migrations.DeleteModel(
            name='Iso27701V2019',
        ),
        migrations.DeleteModel(
            name='Iso29100V2011',
        ),
        migrations.DeleteModel(
            name='Iso31000V2009',
        ),
        migrations.DeleteModel(
            name='Iso31010V2009',
        ),
        migrations.DeleteModel(
            name='Minimumsecurityrequirementsmcc',
        ),
        migrations.DeleteModel(
            name='Nist800160',
        ),
        migrations.DeleteModel(
            name='Nist800161Rev1',
        ),
        migrations.DeleteModel(
            name='Nist800161Rev1Cscrmbaseline',
        ),
        migrations.DeleteModel(
            name='Nist800161Rev1FlowDown',
        ),
        migrations.DeleteModel(
            name='Nist800161Rev1Level1',
        ),
        migrations.DeleteModel(
            name='Nist800161Rev1Level2',
        ),
        migrations.DeleteModel(
            name='Nist800161Rev1Level3',
        ),
        migrations.DeleteModel(
            name='Nist800171A',
        ),
        migrations.DeleteModel(
            name='Nist800171Rev2',
        ),
        migrations.DeleteModel(
            name='Nist800172',
        ),
        migrations.DeleteModel(
            name='Nist800218V11',
        ),
        migrations.DeleteModel(
            name='Nist80037Rev2',
        ),
        migrations.DeleteModel(
            name='Nist80039',
        ),
        migrations.DeleteModel(
            name='Nist80053Rev4',
        ),
        migrations.DeleteModel(
            name='Nist80053Rev4High',
        ),
        migrations.DeleteModel(
            name='Nist80053Rev4Low',
        ),
        migrations.DeleteModel(
            name='Nist80053Rev4Moderate',
        ),
        migrations.DeleteModel(
            name='Nist80053Rev5',
        ),
        migrations.DeleteModel(
            name='Nist80053Rev5High',
        ),
        migrations.DeleteModel(
            name='Nist80053Rev5Low',
        ),
        migrations.DeleteModel(
            name='Nist80053Rev5Moderate',
        ),
        migrations.DeleteModel(
            name='Nist80053Rev5Noc',
        ),
        migrations.DeleteModel(
            name='Nist80053Rev5Privacy',
        ),
        migrations.DeleteModel(
            name='Nist80063BPartialmapping',
        ),
        migrations.DeleteModel(
            name='Nist80082Rev2Highimpacticsoverl',
        ),
        migrations.DeleteModel(
            name='Nist80082Rev2Lowimpacticsoverla',
        ),
        migrations.DeleteModel(
            name='Nist80082Rev2Moderateimpacticso',
        ),
        migrations.DeleteModel(
            name='Nistarmfai1001V1',
        ),
        migrations.DeleteModel(
            name='Nistcsfv11',
        ),
        migrations.DeleteModel(
            name='Nistprivacyframeworkv1',
        ),
        migrations.DeleteModel(
            name='Nistssdf',
        ),
        migrations.DeleteModel(
            name='Owasptop10V2021',
        ),
        migrations.DeleteModel(
            name='Pcidssv32',
        ),
        migrations.DeleteModel(
            name='Pcidssv40',
        ),
        migrations.DeleteModel(
            name='ScfbbusinessmergersAcquisition',
        ),
        migrations.DeleteModel(
            name='Scfeembeddedtechnology',
        ),
        migrations.DeleteModel(
            name='Scficyberinsurance',
        ),
        migrations.DeleteModel(
            name='Scfrransomwareprotection',
        ),
        migrations.DeleteModel(
            name='Usc2M2V21',
        ),
        migrations.DeleteModel(
            name='Uscertrmmv12',
        ),
        migrations.DeleteModel(
            name='Uscmmc20Level1',
        ),
        migrations.DeleteModel(
            name='Uscmmc20Level2',
        ),
        migrations.DeleteModel(
            name='Uscmmc20Level3',
        ),
        migrations.DeleteModel(
            name='Ushipaa',
        ),
        migrations.DeleteModel(
            name='Ussox',
        ),
        migrations.AlterModelOptions(
            name='seleccionassessment',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='evidencerequestcatalog',
            table='evidencerequestcatalog',
        ),
    ]
