# Generated by Django 4.2.2 on 2023-08-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_asociacionevidenciascreadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iniciativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.TextField(db_column='Descripcion')),
            ],
            options={
                'db_table': 'iniciativas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposIniciativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
            ],
            options={
                'db_table': 'tipos_iniciativas',
                'managed': False,
            },
        ),
    ]
