# Generated by Django 4.2.2 on 2023-07-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_usuarios_evidencias_delete_ciscscv8_delete_cobit2019_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='seleccionassessment',
            table='homepage_seleccionassessment',
        ),
    ]
