# Generated by Django 4.2.2 on 2023-08-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_assessmentes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaturirtyTableEs',
            fields=[
                ('ccmmcod', models.CharField(blank=True, db_column='CCMMCOD', max_length=255, null=True)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
                ('sublevels', models.CharField(db_column='SUBLEVELS', max_length=255, primary_key=True, serialize=False)),
                ('percentage', models.FloatField(blank=True, db_column='PERCENTAGE', null=True)),
            ],
            options={
                'db_table': 'maturirty_table_es',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='maturirtytable',
            table='maturirty_table',
        ),
    ]
