# Generated by Django 4.2.2 on 2023-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_maturirtytablees_alter_maturirtytable_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidencerequestcatalogEs',
            fields=[
                ('evidence_request_references', models.CharField(db_column='Evidence Request References', max_length=255, primary_key=True, serialize=False)),
                ('area_of_focus', models.CharField(blank=True, db_column='Area of Focus', max_length=255, null=True)),
                ('artifact', models.CharField(blank=True, db_column='Artifact', max_length=255, null=True)),
                ('artifact_description', models.TextField(blank=True, db_column='Artifact Description', null=True)),
                ('control_mappings', models.CharField(blank=True, db_column='Control Mappings', max_length=255, null=True)),
                ('comentario2', models.TextField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evidencerequestcatalog_es',
                'managed': False,
            },
        ),
    ]
