# Generated by Django 4.2.2 on 2023-08-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_evidencerequestcataloges'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsociacionUsuariosProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asociacion_usuarios_proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.CharField(blank=True, max_length=300, null=True)),
                ('alcance', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=100, null=True)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
    ]
