# Generated by Django 4.2.2 on 2023-08-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_asociacionusuariosproyecto_cliente_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsociacionProyectoAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asociacion_proyecto_assessment',
                'managed': False,
            },
        ),
    ]
