# Generated by Django 4.2.2 on 2023-09-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_asociacionproyectoassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsociacionProyectoMejoraIniciativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asociacion_proyecto_mejora_iniciativa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entrevistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('grupocontroles', models.TextField(blank=True, db_column='grupoControles', null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('duracionestimada', models.TimeField(blank=True, db_column='duracionEstimada', null=True)),
                ('duracionreal', models.TimeField(blank=True, db_column='duracionReal', null=True)),
            ],
            options={
                'db_table': 'entrevistas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanProyectosMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('riesgos', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('duracion', models.TimeField(blank=True, null=True)),
                ('coste', models.FloatField(blank=True, null=True)),
                ('beneficio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_proyectos_mejora',
                'managed': False,
            },
        ),
    ]
