# Generated by Django 4.2.2 on 2023-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_asociacionproyectomejorainiciativa_entrevistas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsociacionEntrevistasUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asociacion_entrevistas_usuarios',
                'managed': False,
            },
        ),
    ]
