# Generated by Django 4.2.2 on 2023-09-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_asociacionentrevistasusuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsociacionPlanProyectosProyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asociacion_plan_proyectos_proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlanProyectoMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plan_proyecto_mejora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProyectosMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('riesgos', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, null=True)),
                ('duracion', models.FloatField(blank=True, null=True)),
                ('coste', models.FloatField(blank=True, null=True)),
                ('beneficio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyectos_mejora',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='PlanProyectosMejora',
        ),
    ]
