# Generated by Django 4.2.2 on 2023-07-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('puede_exportar', 'Puede exportar assessment'), ('puede_importar', 'Puede importar algun assessment'), ('puede_Mantener_tablas', 'Puede entrar al mantenimeinto de las tablas'), ('puede_crear_assesment', 'Puede crear assessments'), ('puede_ver_assesment', 'Puede ver los assessments'))},
        ),
    ]
